---
# Copyright 2021, 2022. Kyndryl All Rights Reserved.
# #
# # Licensed under the Apache License, Version 2.0 (the "License");
# # you may not use this file except in compliance with the License.
# # You may obtain a copy of the License at
# #
# # https://www.apache.org/licenses/LICENSE-2.0
# #
# # Unless required by applicable law or agreed to in writing, software
# # distributed under the License is distributed on an "AS IS" BASIS,
# # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# # See the License for the specific language governing permissions and
# # limitations under the License.
# #

#AWS VPC configs
vpc_cidr: <Enter details as per landing zone>
public_subnet_cidr: <Enter details as per landing zone>
private_subnet_cidr: <Enter details as per landing zone>
aws_region: <Enter details as per landing zone>
hostname: <Enter details as per landing zone - Unused>
aws_ssh_key:	<Enter details as per landing zone - Unused>
aws_security_group: <Enter details as per landing zone - Unused>
local_private_key_path: "Unused in this example"

# OpenVPN configs
vpn_config: awsvpnserver <Used for the OpenVPN certificates, Jinja template and service>
route_all_traffic: true
dns_server_1:
dns_server_2:
openvpn_port: 1194
openvpn_protocol: tcp #udp
openvpn_cidr: 10.8.0.0/24 <See more details on OpenVPN man pages>
certificate_prefix: awsvpnserver
...